export const COMMANDS = {
	GET_PRODUCTS: "get_products",
	CREATE_PRODUCT: "create_product",
	UPDATE_PRODUCT: "update_product",
	DELETE_PRODUCT: "delete_product",
	CHECK_AVAILABILITY: "check_availability",
	GET_LATEST_AVAILABILITY: "get_latest_availability",
	GET_AVAILABILITY_HISTORY: "get_availability_history",
	GET_SETTINGS: "get_settings",
	UPDATE_SETTINGS: "update_settings",
	SEND_NOTIFICATION: "send_notification",
	CLOSE_SPLASHSCREEN: "close_splashscreen",
	CHECK_FOR_UPDATE: "check_for_update",
	DOWNLOAD_AND_INSTALL_UPDATE: "download_and_install_update",
	GET_CURRENT_VERSION: "get_current_version",
} as const;
